### ISSUE TITLE
Support shutdown/get_user_version for RecoveryDatabase

### ISSUE THREAD

**Issue by stoically** [stoically/radical-native#19]
https://github.com/vector-im/riot-desktop/pull/104

**Comment by poljar** [comment]
You don't need to expose this over your IPC, you can skip the reindex if the user version is 0 and just delete the db as shown here https://github.com/vector-im/riot-desktop/pull/104/files#diff-1aa0440c816c324539d613c67b9ea3faR469.

The reason for this is, the reindex is too slow for larger accounts and quite noticeable, since we want to delete the whole thing anyways it's fine to delete it when the reindex is requested. For the next reindex we'll need to figure out some type of UI.

**Comment by stoically** [comment]
@poljar Thanks for the explanation

Added in v0.1beta15
